### ISSUE TITLE
Saved volume not applied on launch

### ISSUE THREAD

**Issue by tobytaken** [jt-owo/tune#54]
**Describe the bug**
On launch, the previously set volume is displayed on the volume slider, but playback always starts at 100% volume unless changed.

**To Reproduce**
1. Launch tune
2. Set volume to 20% for example.
3. Relaunch tune (volume slider displays 20% from last session)
4. Play song (song plays at 100% volume regardless of last sessions setting)

**Comment by jt-owo** [comment]
Got fixed with #55
